### ISSUE TITLE
老师好!

### ISSUE THREAD

**Issue by huiyuanjian** [zce/music#2]
您这个音乐播放器在桌面双击就可以运行的视频教程可以发给我分吗?

**Comment by zce** [comment]
...这里是issues，别当留言板使好不好

**Comment by roy-lau** [comment]
留言板在哪(怎么才能搞到打包成exe的视频)？
我也想要怎么打包成exe的视频！

**Comment by zce** [comment]
GitHub 没有留言板，这种问题可以发邮件。
PS：视频我自己也没有留，上网找找吧

**Comment by roy-lau** [comment]
👌 O(∩_∩)O好的！
